<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/09/13 21:23:40

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=deltamarine;host=localhost',
  'username' => 'deltamarine',
  'password' => 'delt@55!marine',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
