<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/09/13 21:13:49
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
