<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/09/13 21:17:07
$this->security = array (
  'index' => 
  array (
    'credentials' => 'customer_view',
  ),
  'add' => 
  array (
    'credentials' => 'customer_edit',
  ),
  'view' => 
  array (
    'credentials' => 'customer_view',
  ),
  'edit' => 
  array (
    'credentials' => 'customer_edit',
  ),
  'delete' => 
  array (
    'credentials' => 'customer_edit',
  ),
  'boatadd' => 
  array (
    'credentials' => 'customer_edit',
  ),
  'boatedit' => 
  array (
    'credentials' => 'customer_edit',
  ),
  'boatdelete' => 
  array (
    'credentials' => 'customer_edit',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'app_admin',
  ),
);
