<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/11/27 06:44:59
sfConfig::add(array(
  'app_wf_crm_plugin_routes_register' => true,
  'app_wf_crm_plugin_use_bundled_layout' => true,
  'app_wf_crm_plugin_use_bundled_stylesheet' => true,
  'app_wf_crm_plugin_subscribe_form' => array (
  'display' => 
  array (
    0 => 'first_name',
    1 => 'middle_name',
    2 => 'last_name',
    3 => 'salutation',
    4 => 'titles',
    5 => 'job_title',
    6 => 'alpha_name',
    7 => 'email',
    8 => 'work_phone',
    9 => 'mobile_phone',
    10 => 'home_phone',
    11 => 'fax',
    12 => 'homepage',
    13 => 'public_notes',
    14 => 'wf_crm_category_ref_list',
  ),
  'fields' => 
  array (
    'first_name' => 
    array (
      'required' => true,
      'required_msg' => 'First Name required.',
    ),
    'last_name' => 
    array (
      'required' => true,
    ),
    'email' => 
    array (
      'required' => true,
    ),
    'wf_crm_category_ref_list' => 
    array (
      'label' => 'Categories',
      'required' => true,
    ),
  ),
),
  'app_wf_crm_plugin_contactus_form' => array (
  'email_notification' => 
  array (
    'enable' => true,
    'subject' => 'mail subject',
    'address' => 'mail@local',
  ),
  'display' => 
  array (
    0 => 'first_name',
    1 => 'last_name',
    2 => 'email',
    3 => 'mobile_phone',
    4 => 'public_notes',
  ),
  'fields' => 
  array (
    'first_name' => 
    array (
      'required' => true,
      'required_msg' => 'First Name required.',
    ),
    'last_name' => 
    array (
      'required' => true,
    ),
    'email' => 
    array (
      'required' => true,
    ),
    'public_notes' => 
    array (
      'required' => true,
      'label' => 'Message',
      'required_msg' => 'Enter message.',
    ),
  ),
),
  'app_sf_guard_plugin_remember_key_expiration_age' => 2592000,
  'app_sf_guard_plugin_remember_cookie_name' => 'delta_rk',
  'app_sf_guard_plugin_signin_form' => 'sfGuardFormSigninCustom',
  'app_hst_rate' => 12,
  'app_pst_rate' => 7,
  'app_gst_rate' => 5,
  'app_workorder_default_tasks' => array (
  0 => 'Admin & Project Mgmt',
  1 => 'Product Sourcing & Ordering',
  2 => 'Install Protective Coverings',
  3 => 'Clean Up/Final Clean Up',
  4 => 'Freight & Customs',
  5 => 'Boat Equipment & Contents',
),
));
