<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/05 00:31:02
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
