<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/05 11:30:32
$this->security = array (
  'index' => 
  array (
    'credentials' => 'parts_supplier_view',
  ),
  'view' => 
  array (
    'credentials' => 'parts_supplier_view',
  ),
  'edit' => 
  array (
    'credentials' => 'parts_supplier_edit',
  ),
  'add' => 
  array (
    'credentials' => 'parts_supplier_edit',
  ),
  'delete' => 
  array (
    'credentials' => 'parts_supplier_edit',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'app_admin',
  ),
);
