<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/11 11:50:50
$this->security = array (
  'index' => 
  array (
    'credentials' => 'orders_view',
  ),
  'add' => 
  array (
    'credentials' => 'orders_edit',
  ),
  'additem' => 
  array (
    'credentials' => 'orders_edit',
  ),
  'delete' => 
  array (
    'credentials' => 'orders_edit',
  ),
  'edititem' => 
  array (
    'credentials' => 'orders_edit',
  ),
  'deleteitem' => 
  array (
    'credentials' => 'orders_edit',
  ),
  'changestatus' => 
  array (
    'credentials' => 'orders_edit',
  ),
  'receiveitems' => 
  array (
    'credentials' => 'orders_receive',
  ),
  'invoice' => 
  array (
    'credentials' => 'orders_view',
  ),
  'changeexpecteddate' => 
  array (
    'credentials' => 'orders_edit',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'app_admin',
  ),
);
