<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/05 11:06:32
$this->security = array (
  'index' => 
  array (
    'credentials' => 'sales_view',
  ),
  'add' => 
  array (
    'credentials' => 'sales_edit',
  ),
  'additem' => 
  array (
    'credentials' => 'sales_edit',
  ),
  'delete' => 
  array (
    'credentials' => 'sales_edit',
  ),
  'edititem' => 
  array (
    'credentials' => 'sales_edit',
  ),
  'deleteitem' => 
  array (
    'credentials' => 'sales_edit',
  ),
  'changestatus' => 
  array (
    'credentials' => 'sales_edit',
  ),
  'shipitems' => 
  array (
    'credentials' => 'sales_ship',
  ),
  'returnitems' => 
  array (
    'credentials' => 'sales_returns',
  ),
  'deletereturn' => 
  array (
    'credentials' => 'sales_returns',
  ),
  'addpayment' => 
  array (
    'credentials' => 'sales_payments',
  ),
  'deletepayment' => 
  array (
    'credentials' => 'sales_payments',
  ),
  'quickcheckout' => 
  array (
    'credentials' => 
    array (
      0 => 'sales_edit',
      1 => 'sales_approve',
      2 => 'sales_ship',
      3 => 'sales_payments',
    ),
  ),
  'invoice' => 
  array (
    'credentials' => 'sales_view',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'app_admin',
  ),
);
