<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/16 09:23:35
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
