<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/11 11:50:50
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
