<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/05 00:30:51
$this->security = array (
  'index' => 
  array (
    'credentials' => 'timelogs_view',
  ),
  'changestatus' => 
  array (
    'credentials' => 'timelogs_approve',
  ),
  'save' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'timelogs_view',
        1 => 'timelogs_add_other',
        2 => 'timelogs_add_self',
      ),
    ),
  ),
  'labour' => 
  array (
    'credentials' => 'timelogs_labour',
  ),
  'labouredit' => 
  array (
    'credentials' => 'timelogs_labour',
  ),
  'labourdelete' => 
  array (
    'credentials' => 'timelogs_labour',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'app_admin',
  ),
);
