<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/16 09:23:35
$this->security = array (
  'index' => 
  array (
    'credentials' => 'parts_manufacturer_view',
  ),
  'view' => 
  array (
    'credentials' => 'parts_manufacturer_view',
  ),
  'edit' => 
  array (
    'credentials' => 'parts_manufacturer_edit',
  ),
  'add' => 
  array (
    'credentials' => 'parts_manufacturer_edit',
  ),
  'delete' => 
  array (
    'credentials' => 'parts_manufacturer_edit',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'app_admin',
  ),
);
