<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/05 00:32:35
$this->security = array (
  'index' => 
  array (
    'credentials' => 'employee_view',
  ),
  'view' => 
  array (
    'credentials' => 'employee_view',
  ),
  'edit' => 
  array (
    'credentials' => 'employee_edit',
  ),
  'add' => 
  array (
    'credentials' => 'employee_edit',
  ),
  'delete' => 
  array (
    'credentials' => 'employee_edit',
  ),
  'useredit' => 
  array (
    'credentials' => 'employee_login',
  ),
  'permsload' => 
  array (
    'credentials' => 'employee_permissions',
  ),
  'permsedit' => 
  array (
    'credentials' => 'employee_permissions',
  ),
  'department' => 
  array (
    'credentials' => 'employee_departments',
  ),
  'departmentedit' => 
  array (
    'credentials' => 'employee_departments',
  ),
  'departmentdelete' => 
  array (
    'credentials' => 'employee_departments',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'app_admin',
  ),
);
