<?php
// auto-generated by sfRoutingConfigHandler
// date: 2020/09/13 21:26:51
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'dashboard',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
