<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/09/13 21:26:51
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'app_admin',
  ),
);
