dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=deltamarine;host=localhost
      username:   deltamarine
      password:   'delt@55!marine'
      encoding:   utf8
      persistent: true
      pooling:    true
