<?php
// auto-generated by sfRoutingConfigHandler
// date: 2014/06/05 08:14:45
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'general',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default_rest' => new sfRoute('/rest/:action', array (
  'module' => 'rest',
), array (
), array (
)),
'default_rest_id' => new sfRoute('/rest/:action/:id', array (
  'module' => 'rest',
), array (
  'id' => '\\d+',
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
