<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/05 08:14:45

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=deltamarine;host=localhost',
  'username' => 'deltamarine',
  'password' => 'delt@55!marine',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
